knp_paginator:
  page_range: 5          # number of links shown in the pagination menu
  default_options:
    page_name: page    # page query parameter name
    sort_field_name: sort  # sort field query parameter name
    sort_direction_name: direction  # sort direction query parameter name
    distinct: true     # ensures distinct results
  template:
    pagination: '@KnpPaginator/Pagination/sliding.html.twig'  # sliding pagination template
    sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'  # sorting link template
