vich_uploader:
    db_driver: orm
    mappings:
        destination_images:
            uri_prefix: /images/destinations
            upload_destination: '%kernel.project_dir%/public/images/destinations'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer: null
            delete_on_update: true
            delete_on_remove: true
