version: '3.8'

services:
  php:
    build:
      context: ./.docker/php
    container_name: travel_php
    volumes:
      - .:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: travel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: travel
      MYSQL_USER: travel
      MYSQL_PASSWORD: travel
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
      - ./.docker/mysql/init:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:alpine
    container_name: travel_nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/:/etc/nginx/conf.d/
    depends_on:
      - php

volumes:
  mysql_data:
